"""
MINATO COAST - the modular bridge kit.

Builds the coral-vermilion steel through-arch crossing as a set of INDEPENDENT modules that
Unity instances along the route, plus the JSON spec that keeps the Blender geometry and the
Unity staging pass agreeing about every dimension.

Authored in Unity-local coordinates (+Z forward along the route, +X rider's right, +Y up) and
converted by ``minato_lib``'s beam/tube/prism primitives, which all pass through
``sakura_lib.u2b``. See ``minato_lib`` for the measured FBX round trip.

WHY THESE ARE MODULES AND THE ROAD IS NOT
-----------------------------------------
The brief asks for BOTH "modular bridge pieces" AND "smooth continuous road ... no gaps,
overlaps, bumps, snagging seams, or collider discontinuities". Those pull in opposite
directions: a chain of straight tiles across a curving route cannot be seam-free.

So the split is by what each side is actually good at:

  * Everything the rider RIDES ON or ALONGSIDE - carriageway, markings, kerb, parapet, handrail
    runs, guardrail - is swept as ONE continuous mesh along the route by the Unity pass
    (``MinatoCoastEnvironment``), sharing exact vertices across chunk boundaries. No tiling, so
    no seam can exist.
  * Everything STRUCTURAL and genuinely discrete - arch spans, piers, deck girders, railing
    posts, lamps, expansion joints - is a module here, instanced with clean pivots and LODs.

The one module that sits under the road, the deck bay, is 13.75 m long. On the tightest curve
the bridge actually uses (the ~400 m radius landfall) a straight 13.75 m chord deviates by
13.75^2 / (8 * 400) = 59 mm from the true arc - hidden under the parapet overhang, and never
touched by the rider or a collider.

ALL DIMENSIONS ARE PROVISIONAL ILLUSTRATIVE TUNING unless noted. They are chosen to read like
the concept renders at cycling-camera scale and to be structurally believable, not because the
design fixes them.
"""

import json
import math
import os
import sys

import bpy
from mathutils import Vector

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sakura_lib as S  # noqa: E402
import minato_lib as M  # noqa: E402


# ======================================================================== spec
#
# Emitted to Assets/Environment/MinatoCoast/MinatoBridgeSpec.json so the Unity staging pass
# reads the SAME numbers rather than duplicating them. Changing a value here changes both.

SPEC = {
    # ---- deck cross-section (metres either side of the carriageway centreline) ----
    # SPEC 2026-09-22: road width target 7-9 m -> 8.0 m carriageway (half 4.0).
    "carriagewayHalfWidth": 4.0,    # matches MinatoRoute.json roadHalfWidth
    "shoulderWidth": 0.55,
    "kerbWidth": 0.45,
    "parapetWidth": 0.60,
    "footwayWidth": 0.50,
    "walkwayWidth": 1.40,           # maintenance walkway outboard of the girder
    "deckHalfWidth": 6.10,          # structural edge of the deck slab
    "deckSlabDepth": 0.45,
    "girderDepth": 2.60,
    "girderOffset": 4.80,           # longitudinal plate girders at +/- this
    "kerbHeight": 0.16,
    "parapetHeight": 1.05,          # concrete upstand
    # SPEC 2026-09-22: guardrails ~1.1 m. This is the rail top above the deck surface.
    "railHeight": 1.10,

    # ---- arch ----
    # SPEC 2026-09-22: arch spans 80-140 m -> 120 m. Rise/span held at 0.20 (through-arch
    # convention is 1/5 to 1/6), so the 46 m rise on the old 220 m span scales to 24 m.
    "spanLength": 120.0,            # THE headline module length
    "archRise": 24.0,
    "ribOffsetSpring": 6.90,        # rib centre at the springing
    "ribOffsetCrown": 5.50,         # ribs converge over the deck
    # Rib sections scale with the shorter span (~0.78x) so the arch does not read as stumpy.
    "ribWidthSpring": 1.90,
    "ribDepthSpring": 2.80,
    "ribWidthCrown": 1.40,
    "ribDepthCrown": 1.80,
    "hangerSpacing": 12.0,          # one hanger pair per deck bay
    "hangerRadius": 0.085,
    "archSegments": 26,

    # ---- piers ----
    "pierCapDepth": 5.50,
    "pierCapHalfWidth": 8.00,
    "pierCapHalfLength": 6.00,
    "pierShaftLength": 10.0,        # tileable segment
    "pierShaftHalfWidth": 4.60,
    "pierShaftHalfLength": 3.40,
    "pierBaseDepth": 11.00,         # waterline block with cutwaters

    # ---- repeats ----
    # 10 deck bays per 120 m span, one hanger pair per bay.
    "deckBayLength": 12.0,
    "railPostSpacing": 2.50,
    "lampSpacing": 55.0,
    "jointEverySpan": True,
}


def write_spec():
    path = os.path.join(M.minato_dir(), "MinatoBridgeSpec.json")
    payload = dict(SPEC)
    payload["_comment"] = ("Generated by tools/blender/build_minato_bridge.py - the single "
                           "source of truth shared by the Blender modules and "
                           "MinatoCoastEnvironment.cs. Do not edit by hand.")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=1, sort_keys=True)
    print(f"[minato] wrote {os.path.relpath(path, S.repo_root())}")
    return path


K = SPEC  # shorthand


# ======================================================================== arch span

def _arch_f(z):
    """Normalised 0..1 position along the span from a local Z."""
    return (z + K["spanLength"] * 0.5) / K["spanLength"]


def _arch_y(f):
    """Rib centreline height above deck level at normalised position f."""
    return K["archRise"] * (1.0 - (2.0 * f - 1.0) ** 2) - 2.0


def _arch_lean(f):
    return abs(2.0 * f - 1.0)           # 1 at the springing, 0 at the crown


def _arch_x(f, sgn=1.0):
    """Rib centreline offset from the carriageway centreline."""
    lean = _arch_lean(f)
    return sgn * (K["ribOffsetCrown"] +
                  (K["ribOffsetSpring"] - K["ribOffsetCrown"]) * lean)


def _arch_sec(f, scale=1.0):
    """Rib box section (width, depth) at normalised position f."""
    lean = _arch_lean(f)
    w = K["ribWidthCrown"] + (K["ribWidthSpring"] - K["ribWidthCrown"]) * lean
    d = K["ribDepthCrown"] + (K["ribDepthSpring"] - K["ribDepthCrown"]) * lean
    return w * scale, d * scale


def _build_rib(name, sec_scale=1.0, stiffeners=True):
    """
    ONE arch rib, origin at the span centre on the carriageway centreline at deck level.
    Unity instances this twice (mirrored in X) per span - the spec forbids baking the whole
    arch into a single mesh, so the rib is the atomic module.
    """
    n = K["archSegments"]
    span = K["spanLength"]
    half = span * 0.5
    pts, secs = [], []
    for i in range(n + 1):
        f = i / n
        pts.append((_arch_x(f), _arch_y(f), -half + f * span))
        secs.append(_arch_sec(f, sec_scale))

    steel = []
    for i in range(n):
        w0, d0 = secs[i]
        w1, d1 = secs[i + 1]
        steel.append(M.beam(f"rib_{i}", pts[i], pts[i + 1],
                            w0, d0, up_hint=(0, 1, 0), uv_per_m=0.30,
                            taper=(w1 / max(w0, 1e-6))))
    if stiffeners:
        # Visible stiffener plates down the outside face of a welded box arch.
        for i in range(2, n - 1, 2):
            a = Vector(pts[i])
            w, d = secs[i]
            steel.append(M.box(f"rib_st{i}", (a.x + w * 0.5 + 0.06, a.y, a.z),
                               (0.10, d * 0.88, 0.55), uv_per_m=0.6))

    obj = M.finish(steel, "steel", bevel=0.035, bevel_segments=1, smooth_angle=32.0)
    M.paint(obj, "steel_vermilion")
    obj.name = name
    return obj


def build_arch_rib_main():
    """Main arch rib - full section, carries the hangers."""
    return _build_rib("Minato_Bridge_ArchRibMain_LOD0", sec_scale=1.0, stiffeners=True)


def build_arch_rib_secondary():
    """
    Secondary arch rib - the lighter inboard/approach rib. Same curve so it reads as one
    family, 68% section so the pair has a visible primary/secondary hierarchy.
    """
    return _build_rib("Minato_Bridge_ArchRibSecondary_LOD0", sec_scale=0.68, stiffeners=False)


def build_hanger():
    """
    One vertical hanger of nominal 10 m length with its deck socket casting, origin at the
    DECK end. Unity scales it along Y to reach the rib, so a single module serves every
    hanger on the crossing.
    """
    parts = [
        M.tube("hang", (0.0, 0.0, 0.0), (0.0, 10.0, 0.0),
               K["hangerRadius"], segments=8, uv_per_m=0.7),
        M.box("sock", (0.0, 0.22, 0.0), (0.28, 0.44, 0.28), uv_per_m=1.2),
        M.box("shoe", (0.0, 9.86, 0.0), (0.22, 0.30, 0.22), uv_per_m=1.2),
    ]
    obj = M.finish(parts, "grey", bevel=0.02, bevel_segments=1, smooth_angle=32.0)
    M.paint(obj, "steel_dark")
    obj.name = "Minato_Bridge_Hanger_LOD0"
    return obj


def build_cross_brace():
    """
    Horizontal crown strut ONLY, spanning between the two ribs. Origin at the carriageway
    centreline on the rib centreline height. Unity scales X to the rib gap at each station.

    The diagonal members are deliberately NOT in this module: a rib curves between two brace
    stations, so a diagonal baked in at constant height renders as a flat plate punching out
    through the arch silhouette once the module is uniformly scaled. They are placed as
    separate straight members between computed endpoints - see build_brace_diagonal.
    """
    e = K["ribOffsetCrown"] - K["ribWidthCrown"] * 0.25   # embed a quarter-section into the rib
    parts = [M.beam("strut", (-e, 0.0, 0.0), (e, 0.0, 0.0), 0.62, 0.78,
                    up_hint=(0, 1, 0), uv_per_m=0.5)]
    obj = M.finish(parts, "steel", bevel=0.035, bevel_segments=1, smooth_angle=32.0)
    M.paint(obj, "steel_vermilion")
    obj.name = "Minato_Bridge_CrossBrace_LOD0"
    return obj


def build_brace_diagonal():
    """
    One straight diagonal bracing member, nominal 10 m long along Unity +Z, origin at its
    START end. Placed between two computed rib points and scaled along its axis, so it follows
    the arch instead of lying flat across it.
    """
    parts = [M.beam("diag", (0.0, 0.0, 0.0), (0.0, 0.0, 10.0), 0.38, 0.46,
                    up_hint=(0, 1, 0), uv_per_m=0.6)]
    obj = M.finish(parts, "steel", bevel=0.03, bevel_segments=1, smooth_angle=32.0)
    M.paint(obj, "steel_vermilion")
    obj.name = "Minato_Bridge_BraceDiagonal_LOD0"
    return obj


def build_arch_pedestal():
    """Springing pedestal and its steel shoe casting - one per rib end, four per span."""
    conc = [M.prism("ped", [(-2.05, 0.0), (2.05, 0.0), (1.70, 5.4), (-1.70, 5.4)],
                    (0.0, -6.6, 0.0), (0.0, -6.6, 2.9),
                    up_hint=(0, 1, 0), uv_per_m=0.35)]
    grey = [M.box("shoe", (0.0, -1.05, 0.9), (2.9, 1.3, 3.4), uv_per_m=0.5)]
    c = M.finish(conc, "conc", bevel=0.05, bevel_segments=1, smooth_angle=30.0)
    g = M.finish(grey, "grey", bevel=0.02, bevel_segments=1, smooth_angle=32.0)
    M.paint(c, "concrete")
    M.paint(g, "steel_dark")
    return S.join([c, g], "Minato_Bridge_ArchPedestal_LOD0")


def build_walkway():
    """
    Maintenance walkway module, one deck bay long, origin at its inboard edge at deck level.
    Open grid deck on outriggers, outboard of the girder - decorative, so it carries no
    collision in Unity.
    """
    L = K["deckBayLength"]
    w = K["walkwayWidth"]
    parts = [M.box("grid", (w * 0.5, -0.04, L * 0.5), (w, 0.05, L), uv_per_m=1.4)]
    for i in range(3):
        z = L * (0.16 + 0.34 * i)
        parts.append(M.box(f"out{i}", (w * 0.5, -0.18, z), (w, 0.22, 0.14), uv_per_m=1.0))
        parts.append(M.tube(f"stan{i}", (w - 0.06, 0.0, z), (w - 0.06, 1.05, z),
                            0.030, segments=6, uv_per_m=1.0))
    parts.append(M.tube("rail", (w - 0.06, 1.05, 0.0), (w - 0.06, 1.05, L),
                        0.030, segments=6, uv_per_m=1.0))
    obj = M.finish(parts, "grey", bevel=0.012, bevel_segments=1, smooth_angle=34.0)
    M.paint(obj, "steel_dark")
    obj.name = "Minato_Bridge_Walkway_LOD0"
    return obj


def build_drainage():
    """Deck scupper and its downpipe - the drip source for the rust streaking below."""
    parts = [
        M.box("scup", (0.0, -0.10, 0.0), (0.46, 0.22, 0.34), uv_per_m=1.6),
        M.tube("pipe", (0.0, -0.20, 0.0), (0.0, -2.60, 0.0), 0.075, segments=8, uv_per_m=1.0),
        M.box("clamp", (0.0, -1.70, 0.0), (0.20, 0.10, 0.20), uv_per_m=2.0),
        M.tube("spout", (0.0, -2.60, 0.0), (0.34, -2.78, 0.0), 0.075, segments=8, uv_per_m=1.0),
    ]
    obj = M.finish(parts, "grey", bevel=0.012, bevel_segments=1, smooth_angle=34.0)
    M.paint(obj, "steel_dark")
    obj.name = "Minato_Bridge_Drainage_LOD0"
    return obj


def build_connection_plate():
    """
    Bolted splice plate with a bolt ring - scattered onto rib joints and brace ends so the
    steel reads as assembled rather than extruded. One module, many placements.
    """
    import math as _m
    parts = [M.box("plate", (0.0, 0.0, 0.0), (0.06, 0.92, 0.72), uv_per_m=2.0)]
    for i in range(10):
        a = _m.tau * i / 10.0
        y = 0.32 * _m.cos(a)
        z = 0.25 * _m.sin(a)
        parts.append(M.tube(f"bolt{i}", (0.03, y, z), (0.085, y, z),
                            0.032, segments=6, uv_per_m=3.0))
    obj = M.finish(parts, "grey", bevel=0.006, bevel_segments=1, smooth_angle=36.0)
    M.paint(obj, "steel_dark")
    obj.name = "Minato_Bridge_ConnectionPlate_LOD0"
    return obj


def build_guardrail():
    """
    Guardrail module, one rail-post bay long, origin at the post base on the deck surface.
    SPEC 2026-09-22: rail top at 1.10 m above the deck.
    """
    h = K["railHeight"]
    L = K["railPostSpacing"]
    parts = [
        M.box("post", (0.0, h * 0.5, 0.0), (0.085, h, 0.085), uv_per_m=1.6),
        M.box("base", (0.0, 0.035, 0.0), (0.22, 0.07, 0.22), uv_per_m=2.0),
        M.tube("top", (0.0, h, -L * 0.5), (0.0, h, L * 0.5), 0.045, segments=8, uv_per_m=1.0),
        M.tube("mid", (0.0, h * 0.60, -L * 0.5), (0.0, h * 0.60, L * 0.5),
               0.032, segments=6, uv_per_m=1.0),
        M.tube("low", (0.0, h * 0.28, -L * 0.5), (0.0, h * 0.28, L * 0.5),
               0.032, segments=6, uv_per_m=1.0),
    ]
    obj = M.finish(parts, "steel", bevel=0.010, bevel_segments=1, smooth_angle=34.0)
    M.paint(obj, "steel_vermilion")
    obj.name = "Minato_Bridge_Guardrail_LOD0"
    return obj



# ======================================================================== deck bay

def build_deck_bay():
    """
    13.75 m of under-deck structure: twin longitudinal plate girders, cross girders, the soffit
    and the cantilever brackets that carry the footway. Origin at the bay START on the
    carriageway centreline at deck level; the bay runs to +Z.

    The rideable slab itself is NOT here - it is swept continuously by the Unity pass.
    """
    L = K["deckBayLength"]
    go = K["girderOffset"]
    gd = K["girderDepth"]
    slab = K["deckSlabDepth"]
    top = -slab           # underside of the deck slab

    steel = []
    conc = []

    # Longitudinal plate girders, I-section.
    web = 0.14
    flange_w, flange_t = 1.10, 0.10
    for sgn in (-1.0, +1.0):
        x = sgn * go
        steel.append(M.box(f"web{int(sgn)}", (x, top - gd * 0.5, L * 0.5),
                           (web, gd, L), uv_per_m=0.30))
        steel.append(M.box(f"fl_t{int(sgn)}", (x, top - flange_t * 0.5, L * 0.5),
                           (flange_w, flange_t, L), uv_per_m=0.45))
        steel.append(M.box(f"fl_b{int(sgn)}", (x, top - gd + flange_t * 0.5, L * 0.5),
                           (flange_w, flange_t, L), uv_per_m=0.45))
        # Web stiffeners.
        k = 0
        z = 1.72
        while z < L - 0.5:
            steel.append(M.box(f"stf{int(sgn)}_{k}", (x + sgn * 0.14, top - gd * 0.5, z),
                               (0.14, gd - 2 * flange_t, 0.16), uv_per_m=0.8))
            z += 1.72
            k += 1

    # Cross girders and the K-bracing between the two main girders.
    k = 0
    z = 0.0
    while z <= L + 0.01:
        steel.append(M.beam(f"xg{k}", (-go, top - gd + 0.45, z), (go, top - gd + 0.45, z),
                            0.55, 0.85, up_hint=(0, 1, 0), uv_per_m=0.5))
        if z + L / 4.0 <= L + 0.01:
            steel.append(M.beam(f"kb_a{k}", (-go, top - gd + 0.45, z), (0.0, top - 0.35, z + L / 8.0),
                                0.26, 0.30, up_hint=(0, 1, 0), uv_per_m=0.7))
            steel.append(M.beam(f"kb_b{k}", (go, top - gd + 0.45, z), (0.0, top - 0.35, z + L / 8.0),
                                0.26, 0.30, up_hint=(0, 1, 0), uv_per_m=0.7))
        z += L / 4.0
        k += 1

    # Cantilever brackets carrying the footway outside the girders.
    k = 0
    z = 0.86
    while z < L - 0.2:
        for sgn in (-1.0, +1.0):
            steel.append(M.beam(f"cb{int(sgn)}_{k}",
                                (sgn * (go - 0.4), top - 1.35, z),
                                (sgn * (K["deckHalfWidth"] - 0.05), top - 0.06, z),
                                0.16, 0.34, up_hint=(0, 1, 0), uv_per_m=0.8))
        z += 1.72
        k += 1

    # Underside of the concrete deck slab, full deck width. This - NOT a plate under the
    # girders - is what closes the deck against the sky.
    #
    # An earlier pass sealed the soffit across the bottom of the girders instead, which boxed
    # every cross girder and K-brace inside an opaque shell: the under-deck render came back as
    # a smooth floating plank with none of the structure visible, while the tri count happily
    # reported 3,362. An open-soffit plate-girder deck is also what the real thing is - the slab
    # sits ON the girders, so the girders read as deep shadowed beams hanging beneath it.
    conc.append(M.box("slab", (0.0, top - 0.05, L * 0.5),
                      (K["deckHalfWidth"] * 2.0, 0.10, L), uv_per_m=0.22))
    # Edge fascia beam: the deep shadow line that gives a deck its apparent thickness.
    # prism() extrudes along +Z, so its section "right" axis is -X; mirroring the section in
    # its own right axis is what puts the batter on the OUTBOARD face of each edge.
    base_fascia = [(0.0, 0.0), (0.42, -0.14), (0.42, -0.86), (0.0, -1.00)]
    for sgn in (-1.0, +1.0):
        section = [(sr * -sgn, su) for (sr, su) in base_fascia]
        conc.append(M.prism(
            f"fascia{int(sgn)}", section,
            (sgn * K["deckHalfWidth"], top, 0.0),
            (sgn * K["deckHalfWidth"], top, L),
            up_hint=(0, 1, 0), uv_per_m=0.4))

    steel_obj = M.finish(steel, "steel", bevel=0.02, bevel_segments=1, smooth_angle=30.0)
    conc_obj = M.finish(conc, "conc", bevel=0.03, bevel_segments=1, smooth_angle=30.0)
    M.paint(steel_obj, "steel_grey")
    M.paint(conc_obj, "concrete")
    return S.join([steel_obj, conc_obj], "Minato_Bridge_DeckBay_LOD0")


# ======================================================================== piers

def build_pier_cap():
    """Pier head: the cross-head under the deck plus its bearings. Origin at deck soffit."""
    hw = K["pierCapHalfWidth"]
    hl = K["pierCapHalfLength"]
    d = K["pierCapDepth"]
    conc = []
    grey = []

    # Flared cross-head - wider at the top where it picks up the girders.
    conc.append(M.prism(
        "cap",
        [(-hw, 0.0), (hw, 0.0), (hw * 0.80, -d * 0.62), (hw * 0.62, -d),
         (-hw * 0.62, -d), (-hw * 0.80, -d * 0.62)],
        (0.0, -0.55, -hl), (0.0, -0.55, hl), up_hint=(0, 1, 0), uv_per_m=0.28))
    # Drip nib and a band of form-work detail.
    conc.append(M.box("band", (0.0, -0.55 - d * 0.62, 0.0),
                      (hw * 1.66, 0.22, hl * 2.06), uv_per_m=0.4))

    # Bearings under each main girder.
    for sgn in (-1.0, +1.0):
        grey.append(M.box(f"brg{int(sgn)}", (sgn * K["girderOffset"], -0.30, 0.0),
                          (1.50, 0.50, 1.50), uv_per_m=0.7))

    c = M.finish(conc, "conc", bevel=0.05, smooth_angle=28.0)
    g = M.finish(grey, "grey", bevel=0.02, smooth_angle=30.0)
    M.paint(c, "concrete")
    M.paint(g, "steel_dark")
    return S.join([c, g], "Minato_Bridge_PierCap_LOD0")


def build_pier_shaft():
    """
    A tileable 10 m pier shaft segment, origin at its TOP, running down to -10.

    Prismatic on purpose: a tapered tile cannot repeat. The batter that makes a pier look like
    a pier lives in the base module, and the shaft carries vertical form joints and a shallow
    recessed panel so a stack of them never reads as one smooth extrusion.
    """
    L = K["pierShaftLength"]
    hw = K["pierShaftHalfWidth"]
    hl = K["pierShaftHalfLength"]
    parts = [M.box("shaft", (0.0, -L * 0.5, 0.0), (hw * 2, L, hl * 2), uv_per_m=0.24)]
    # Recessed panel on each broad face.
    for sgn in (-1.0, +1.0):
        parts.append(M.box(f"panel{int(sgn)}", (0.0, -L * 0.5, sgn * (hl + 0.005)),
                           (hw * 1.46, L - 1.3, 0.14), uv_per_m=0.35))
    # Vertical corner pilasters.
    for sx in (-1.0, 1.0):
        parts.append(M.box(f"pil{int(sx)}", (sx * (hw - 0.22), -L * 0.5, 0.0),
                           (0.44, L, hl * 2 + 0.16), uv_per_m=0.4))
    obj = M.finish(parts, "shaft", bevel=0.04, smooth_angle=28.0)
    M.paint(obj, "concrete")
    obj.name = "Minato_Bridge_PierShaft_LOD0"
    return obj


def build_pier_base():
    """
    The waterline block: battered on all faces with pointed cutwaters at each end to break the
    sea, plus a rock-armour skirt. Origin at its TOP so it stacks under the shaft.
    """
    d = K["pierBaseDepth"]
    hw = K["pierShaftHalfWidth"]
    hl = K["pierShaftHalfLength"]
    conc = []
    rock = []

    bw, bl = hw + 2.6, hl + 3.4     # footprint at the bottom
    # Battered body.
    conc.append(M.prism(
        "body",
        [(-hw - 0.2, 0.0), (hw + 0.2, 0.0), (bw, -d), (-bw, -d)],
        (0.0, 0.0, -hl - 0.2), (0.0, 0.0, hl + 0.2), up_hint=(0, 1, 0), uv_per_m=0.22))
    # Pointed cutwaters.
    for sgn in (-1.0, +1.0):
        conc.append(M.prism(
            "cut",
            [(-hw - 0.2, 0.0), (hw + 0.2, 0.0), (bw, -d), (-bw, -d)],
            (0.0, 0.0, sgn * (hl + 0.2)), (0.0, 0.0, sgn * bl),
            up_hint=(0, 1, 0), uv_per_m=0.22, taper=0.06))
    # Splash band at the waterline - the tide line is what sells scale on a marine pier.
    conc.append(M.box("splash", (0.0, -d + 1.4, 0.0), (bw * 2.02, 1.3, bl * 2.02),
                      uv_per_m=0.35))

    # Rock armour.
    r = M.rng(7)
    for i in range(26):
        a = r.uniform(0, math.tau)
        rad = r.uniform(0.92, 1.18)
        px = math.cos(a) * bw * rad
        pz = math.sin(a) * bl * rad
        s = r.uniform(0.9, 1.9)
        rock.append(M.box(f"arm{i}", (px, -d + s * 0.35, pz), (s, s * 0.8, s * 1.1),
                          uv_per_m=0.5))

    c = M.finish(conc, "conc", bevel=0.06, smooth_angle=26.0)
    rk = M.finish(rock, "rock", bevel=0.05, smooth_angle=34.0)
    M.paint(c, "concrete_wet")
    M.paint(rk, "rock")
    return S.join([c, rk], "Minato_Bridge_PierBase_LOD0")


# ======================================================================== furniture

def build_rail_post():
    """
    Steel railing post with its base plate and the bracket lugs the handrails bolt through.
    Origin at the top of the concrete parapet. Instanced every 2.5 m; the rails themselves are
    swept continuously by the Unity pass so they cannot develop a seam.
    """
    h = K["railHeight"]
    parts = [
        M.box("plate", (0.0, 0.012, 0.0), (0.26, 0.024, 0.26), uv_per_m=1.2),
        M.beam("post", (0.0, 0.02, 0.0), (0.0, h, 0.0), 0.08, 0.08,
               up_hint=(0, 0, 1), uv_per_m=0.9),
        M.box("cap", (0.0, h + 0.02, 0.0), (0.12, 0.035, 0.12), uv_per_m=1.2),
    ]
    for hy in (h * 0.42, h * 0.98):
        parts.append(M.box(f"lug{hy:.2f}", (0.0, hy, 0.0), (0.16, 0.075, 0.075), uv_per_m=1.4))
    for sx in (-1, 1):
        parts.append(M.box(f"bolt{sx}", (sx * 0.06, 0.03, 0.0), (0.04, 0.03, 0.04),
                           uv_per_m=2.0))
    obj = M.finish(parts, "post", bevel=0.008, smooth_angle=34.0)
    M.paint(obj, "steel_vermilion")
    obj.name = "Minato_Bridge_RailPost_LOD0"
    return obj


def build_lamp():
    """The tall curved lamp standard from concepts 01-04. Origin at its base."""
    grey = []
    h = 9.4
    grey.append(M.prism("foot", [(-0.30, -0.30), (0.30, -0.30), (0.30, 0.30), (-0.30, 0.30)],
                        (0.0, 0.0, 0.0), (0.0, 0.55, 0.0), up_hint=(0, 0, 1), uv_per_m=0.9))
    grey.append(M.tube("column", (0.0, 0.5, 0.0), (0.0, h, 0.0), 0.115, segments=10,
                       uv_per_m=0.7, taper=0.72))
    # Curved gallows arm reaching out over the carriageway.
    prev = Vector((0.0, h, 0.0))
    for i in range(1, 7):
        f = i / 6.0
        nxt = Vector((-(2.5 * f), h + 1.45 * math.sin(f * math.pi * 0.5), 0.0))
        grey.append(M.tube(f"arm{i}", prev, nxt, 0.085 * (1.0 - 0.25 * f), segments=8,
                           uv_per_m=0.8))
        prev = nxt
    grey.append(M.prism("lum", [(-0.30, -0.10), (0.30, -0.10), (0.26, 0.10), (-0.26, 0.10)],
                        (prev.x - 0.05, prev.y - 0.10, -0.62),
                        (prev.x - 0.05, prev.y - 0.10, 0.62),
                        up_hint=(0, 1, 0), uv_per_m=0.9))
    obj = M.finish(grey, "lamp", bevel=0.01, smooth_angle=34.0)
    M.paint(obj, "lamp_grey")
    obj.name = "Minato_Bridge_Lamp_LOD0"
    return obj


def build_joint():
    """
    Expansion joint: the finger plate running across the carriageway at every span end. Sits
    2 cm proud of nothing - it is inset flush into the swept road so it cannot be a bump.
    """
    w = (K["deckHalfWidth"] - 0.2) * 2.0
    parts = [
        M.box("kerb_l", (0.0, -0.02, -0.26), (w, 0.10, 0.20), uv_per_m=1.0),
        M.box("kerb_r", (0.0, -0.02, 0.26), (w, 0.10, 0.20), uv_per_m=1.0),
        M.box("gap", (0.0, -0.05, 0.0), (w, 0.10, 0.34), uv_per_m=1.0),
    ]
    # Interlocking fingers.
    n = int(w / 0.34)
    for i in range(n):
        x = -w * 0.5 + (i + 0.5) * (w / n)
        z = -0.13 if i % 2 == 0 else 0.13
        parts.append(M.box(f"fing{i}", (x, -0.012, z), (w / n * 0.72, 0.055, 0.30),
                           uv_per_m=1.6))
    obj = M.finish(parts, "joint", bevel=0.004, smooth_angle=34.0)
    M.paint(obj, "steel_dark")
    obj.name = "Minato_Bridge_Joint_LOD0"
    return obj


def build_portal():
    """
    A standalone portal frame for the lower approach spans, where the deck runs on plate
    girders rather than under an arch but still needs visible cross bracing.
    """
    parts = []
    hw = K["deckHalfWidth"] + 0.5
    h = 7.2
    for sx in (-1.0, 1.0):
        parts.append(M.beam(f"leg{int(sx)}", (sx * hw, -0.5, 0.0), (sx * (hw - 0.55), h, 0.0),
                            0.85, 0.95, up_hint=(0, 0, 1), uv_per_m=0.4))
    parts.append(M.beam("head", (-(hw - 0.55), h, 0.0), ((hw - 0.55), h, 0.0),
                        0.80, 1.00, up_hint=(0, 1, 0), uv_per_m=0.4))
    parts.append(M.beam("dl", (-(hw - 0.3), h - 2.2, 0.0), (0.0, h - 0.45, 0.0),
                        0.40, 0.48, up_hint=(0, 1, 0), uv_per_m=0.6))
    parts.append(M.beam("dr", ((hw - 0.3), h - 2.2, 0.0), (0.0, h - 0.45, 0.0),
                        0.40, 0.48, up_hint=(0, 1, 0), uv_per_m=0.6))
    obj = M.finish(parts, "portal", bevel=0.03, smooth_angle=32.0)
    M.paint(obj, "steel_vermilion")
    obj.name = "Minato_Bridge_Portal_LOD0"
    return obj


# ======================================================================== export

# (builder, filename, LOD ratios) - the repeated pieces get real LODs because 30+ arch spans
# and 1,300+ deck bays are on screen at once in the ocean chapter.
# SPEC 2026-09-22 LOD ladder: LOD0 full, LOD1 50-60%, LOD2 20-30%, LOD3 5-10%.
LODS = (0.55, 0.25, 0.08)
LODS_SMALL = (0.55, 0.25)        # small props bottom out before a fourth level pays off

KIT = [
    # --- arch, split into atomic modules (the spec forbids one combined bridge mesh) ---
    (build_arch_rib_main,      "Minato_Bridge_ArchRibMain.fbx",      LODS),
    (build_arch_rib_secondary, "Minato_Bridge_ArchRibSecondary.fbx", LODS),
    (build_hanger,             "Minato_Bridge_Hanger.fbx",           LODS_SMALL),
    (build_cross_brace,        "Minato_Bridge_CrossBrace.fbx",       LODS),
    (build_brace_diagonal,     "Minato_Bridge_BraceDiagonal.fbx",    LODS_SMALL),
    (build_arch_pedestal,      "Minato_Bridge_ArchPedestal.fbx",     LODS),
    # --- deck and substructure ---
    (build_deck_bay,   "Minato_Bridge_DeckBay.fbx",   LODS),
    (build_pier_cap,   "Minato_Bridge_PierCap.fbx",   LODS),
    (build_pier_shaft, "Minato_Bridge_PierShaft.fbx", LODS),
    (build_pier_base,  "Minato_Bridge_PierBase.fbx",  LODS),
    # --- furniture and hardware ---
    (build_guardrail,        "Minato_Bridge_Guardrail.fbx",        LODS_SMALL),
    (build_walkway,          "Minato_Bridge_Walkway.fbx",          LODS_SMALL),
    (build_drainage,         "Minato_Bridge_Drainage.fbx",         LODS_SMALL),
    (build_connection_plate, "Minato_Bridge_ConnectionPlate.fbx",  LODS_SMALL),
    (build_rail_post,  "Minato_Bridge_RailPost.fbx",  LODS_SMALL),
    (build_lamp,       "Minato_Bridge_Lamp.fbx",      LODS_SMALL),
    (build_joint,      "Minato_Bridge_Joint.fbx",     LODS_SMALL),
    (build_portal,     "Minato_Bridge_Portal.fbx",    LODS),
]


def main():
    write_spec()
    for builder, filename, ratios in KIT:
        S.reset_scene()
        obj = builder()
        M.stat(obj, filename.replace(".fbx", ""))
        exports = [obj]
        base = obj.name.replace("_LOD0", "")
        for i, r in enumerate(ratios):
            lod = M.decimated_copy(obj, f"{base}_LOD{i + 1}", r)
            exports.append(lod)
        M.export_fbx(exports, filename)
        M.save_blend(filename.replace(".fbx", ".blend"))


if __name__ == "__main__":
    main()
