"""
Nagisa Bay audio map (worker H, 2026-10-01).

Bakes, from Assets/Environment/NagisaBay/NagisaRoute.json + NagisaGround.bytes, the data the positional
ambience needs at runtime so the game never has to scan the ground field:

  * ShoreX/ShoreZ/ShoreDist: for every 50 m of route, the nearest shoreline point (world XZ) and the
    metres from the route to it (positive = route is on land, negative = route is over water, e.g. the bridge).
  * Zone distances (marina end, beach, hotel, climb, KOM, ridge, coast, bridge, finish).

Output: Assets/Ride/Audio/NagisaAudioMap.cs (generated, do not edit).
Run: python tools/audio/build_nagisa_audiomap.py
"""
import json, os, struct
import numpy as np

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
ENV = os.path.join(ROOT, "Assets", "Environment", "NagisaBay")
OUT = os.path.join(ROOT, "Assets", "Ride", "Audio", "NagisaAudioMap.cs")
STEP = 50.0

d = json.load(open(os.path.join(ENV, "NagisaRoute.json")))
b = open(os.path.join(ENV, "NagisaGround.bytes"), "rb").read()
nx, nz = struct.unpack("ii", b[4:12])
x0, z0, cell = struct.unpack("fff", b[12:24])
n = nx * nz
o = 24 + 4 * n + n
SD = np.frombuffer(b[o:o + 4 * n], "<f4").reshape(nz, nx)


def sd(x, z):
    fx, fz = (x - x0) / cell, (z - z0) / cell
    ix = int(np.clip(np.floor(fx), 0, nx - 2)); iz = int(np.clip(np.floor(fz), 0, nz - 2))
    tx, tz = fx - ix, fz - iz
    a = SD[iz, ix] * (1 - tx) + SD[iz, ix + 1] * tx
    c = SD[iz + 1, ix] * (1 - tx) + SD[iz + 1, ix + 1] * tx
    return float(a * (1 - tz) + c * tz)


S = d["samples"]
P = np.array([s["p"] for s in S]); D = np.array([s["d"] for s in S])
sea = float(d.get("seaLevel", 0.0))
L = D[-1]
cnt = int(L // STEP) + 2
sx, sz, sdist = [], [], []
for k in range(cnt):
    dist = min(k * STEP, L)
    i = min(int(np.searchsorted(D, dist)), len(P) - 1)
    x, _, z = P[i]
    h = sd(x, z)
    # gradient of sd points toward land
    c = 6.0
    g = np.array([sd(x + c, z) - sd(x - c, z), sd(x, z + c) - sd(x, z - c)])
    ln = np.linalg.norm(g)
    g = g / ln if ln > 1e-4 else np.array([0.0, 1.0])
    # land->sea direction is -g; shoreline sits |h| metres away along it (h>0: route on land, sea at -g)
    px, pz = x - g[0] * h, z - g[1] * h
    sx.append(px); sz.append(pz); sdist.append(h)


def arr(name, v):
    body = ", ".join(f"{x:.1f}f" for x in v)
    return f"    public static readonly float[] {name} = {{ {body} }};\n"


z = d["zones"]
src = ["// <auto-generated> by tools/audio/build_nagisa_audiomap.py - do not edit by hand. </auto-generated>\n",
       "/// <summary>Baked route/shoreline data for the positional Nagisa Bay ambience (see NagisaAmbienceDirector).</summary>\n",
       "public static class NagisaAudioMap\n{\n",
       f"    public const float StepM = {STEP:.0f}f;\n    public const float RouteLengthM = {L:.1f}f;\n    public const float SeaLevelY = {sea:.2f}f;\n"]
for k, v in z.items():
    src.append(f"    public const float Zone_{k} = {v:.1f}f;\n")
src.append("    /// <summary>Shoreline point (world X, Z) nearest the route every StepM metres.</summary>\n")
src.append(arr("ShoreX", sx)); src.append(arr("ShoreZ", sz))
src.append("    /// <summary>Metres from the route to that shoreline (positive on land, negative over water).</summary>\n")
src.append(arr("ShoreDist", sdist))
src.append("}\n")
open(OUT, "w", newline="\n").write("".join(src))
print("wrote", OUT, cnt, "entries; shore dist min/max", min(sdist), max(sdist))
